[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "catalog-extensions"
version = "0.1.0"
description = "Open edX catalog extensions"
authors = [{name = "CBA"}]
dependencies = []

[tool.setuptools.packages.find]
where = ["src"]
include = [
  "catalog_extensions*",
  "course_discovery.apps.edx_catalog_extensions*"
]
namespaces = true
