# Generated by Django 6.0.4 on 2026-04-30 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseAccreditationMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_key', models.CharField(db_index=True, max_length=255, unique=True)),
                ('ceu_value', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('ceu_label', models.CharField(blank=True, default='CEU', max_length=50)),
                ('pdu_value', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('pdu_label', models.CharField(blank=True, default='PDU', max_length=50)),
                ('credit_text', models.CharField(blank=True, max_length=255)),
                ('accrediting_body', models.CharField(blank=True, max_length=255)),
                ('transcript_display_text', models.CharField(blank=True, max_length=255)),
                ('learning_outcomes', models.JSONField(blank=True, default=list)),
                ('syllabus', models.JSONField(blank=True, default=list)),
                ('prerequisites', models.JSONField(blank=True, default=list)),
                ('references', models.JSONField(blank=True, default=list)),
                ('topics', models.JSONField(blank=True, default=list)),
                ('transcript_language', models.CharField(blank=True, max_length=50)),
                ('duration_text', models.CharField(blank=True, max_length=100)),
                ('category_label', models.CharField(blank=True, max_length=100)),
                ('delivery_mode', models.CharField(blank=True, default='ONLINE', max_length=50)),
                ('price_text', models.CharField(blank=True, max_length=50)),
                ('availability_text', models.CharField(blank=True, max_length=50)),
                ('is_accreditation_approved', models.BooleanField(default=False)),
                ('accreditation_version', models.CharField(blank=True, max_length=50)),
                ('effective_start', models.DateField(blank=True, null=True)),
                ('effective_end', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProgramAccreditationMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_uuid', models.UUIDField(db_index=True, unique=True)),
                ('ceu_total', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('pdu_total', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('credit_text', models.CharField(blank=True, max_length=255)),
                ('accrediting_body', models.CharField(blank=True, max_length=255)),
                ('learning_outcomes', models.JSONField(blank=True, default=list)),
                ('syllabus', models.JSONField(blank=True, default=list)),
                ('prerequisites', models.JSONField(blank=True, default=list)),
                ('references', models.JSONField(blank=True, default=list)),
                ('topics', models.JSONField(blank=True, default=list)),
                ('duration_text', models.CharField(blank=True, max_length=100)),
                ('transcript_language', models.CharField(blank=True, max_length=50)),
                ('category_label', models.CharField(blank=True, max_length=100)),
                ('delivery_mode', models.CharField(blank=True, default='ONLINE', max_length=50)),
                ('price_text', models.CharField(blank=True, max_length=50)),
                ('availability_text', models.CharField(blank=True, max_length=50)),
                ('is_accreditation_approved', models.BooleanField(default=False)),
                ('accreditation_version', models.CharField(blank=True, max_length=50)),
                ('effective_start', models.DateField(blank=True, null=True)),
                ('effective_end', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LearnerCourseCreditRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(db_index=True)),
                ('course_key', models.CharField(db_index=True, max_length=255)),
                ('ceu_awarded', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('pdu_awarded', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('awarded_at', models.DateTimeField(auto_now=True)),
                ('source_certificate_uuid', models.CharField(blank=True, max_length=255)),
                ('credit_text', models.CharField(blank=True, max_length=255)),
                ('accrediting_body', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'unique_together': {('user_id', 'course_key')},
            },
        ),
    ]
